Map<String, String> greetingData = {
  'hugFace': '연애하면 잘 챙겨줄 것 같은 사람은?',
  'heartEyes': '첫 인상이 제일 마음에 들었던 사람은?',
  'victory': '수업에서 팀플을 해보고 싶은 사람은?',
  'popcorn': '같이 영화보러 가고 싶은 사람은?',
  'peeking': '요즘 관심있는 사람은?',
  'oneHundred': '공부를 제일 잘할 것 같은 사람은?',
  'eyes': '좀 더 친해지고 싶은 사람은?',
  'thinkingFace': '나만의 비밀을 공유해줄 수 있는 친구는?',
  'zipperFace': '비밀연애 해보고 싶은 사람은?',
  'sunglassesFace': '옷을 제일 잘 입는 사람은?',
  'fireHeart': '나에게 고백하면 받아줄 수 있는 사람은?',
  'muscle': '몸이 제일 좋아보이는 사람은?',
  'hatchingChick': '볼 때마다 귀엽다고 느껴지는 사람은?',
  'moneyFace' : '가장 돈 많아 보이는 사람은?',
  'mask' : '가장 마기꾼 같은 사람은?',
  'faceInClouds' : '가장 내성적인 사람은?',
  'ghost' : '가장 장난 치고 싶은 사람은?',
  'sleepy' : '수업 시간에 조는 사람은?',
  'rage' : '화나면 가장 무서울 것 같은 사람',
  'sparkles' : '가장 귀티나는 사람은?',
  'dancerWoman' : '가장 춤을 잘 추는 사람은?',
  'clap' : '뭐든 잘하는 사람',
  'speakNoEvilMonkey' : '가장 비밀 잘 지키는 사람',
  'fireworks' : '축제 같이 가고 싶은 사람은?',
  'rollerCoaster' : '놀이공원 같이 가고 싶은 사람은?',
  'cooking' : '가장 요리를 잘하는 사람',
  'crossedFingers' : '가장 MZ 스러운 사람',
  'luck' : '운이 좋은거 같은 사람은?',
  'clinkingBeerMugs' : '너랑 맥주 마시고 싶어 ㅎ',
  'wineGlass' : '소주보단 와인이 잘 어울리는 사람은?',
  'camping' : '너랑 캠핑 가고 싶어 ㅎ',
  'cameraFlash' : '사진이 잘 나오는 사람은?',
  'bowling' : '볼링 제일 잘하는 사람은?',
  'batteryLow' : '요즘 힘들어 보이는 사람은? ㅠ',
  'balanceScale' : '누구에게나 잘하는 사람은?',
  'birthdayCake' : '생일 축하해~',
  'mirrorBall' : '놀땐 노는 사람은?',
  'snowflake' : 'T 100%인 사람',
  'baseball' : '야구장 데이트 하고 싶은 사람',
  'wrappedGift' : '너와 친구 인건 내겐 선물이야',
  'hotBeverage' : '나랑 커피 한잔 하자 ㅎ',
  'volcano' : '화나면 가장 무서울 것 같은 사람',
  'hearNoEvilMonkey' : '고집 셀 것 같은 사람',
  'alien' : '4차원일 것 같은 사람',
  'smileCat' : '친해지기 쉬울 것 같은 사람'
};
